dataset_path: rootsautomation/RICO-ScreenQA-Short
task: "screenqa_short_test"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.screenqa_short_doc_to_visual
doc_to_text: !function utils.screenqa_short_doc_to_text
doc_to_target: "answer"
# The return value of process_results will be used by metrics
process_results: !function utils.screenqa_short_process_results
# Note that the metric name can be either a registed metric function (such as the case for GQA) or a key name returned by process_results
generation_kwargs:
  max_new_tokens: 16
metric_list:
  - metric: screenqa_squad_f1
    aggregation: !function utils.screenqa_short_aggregate_results
    higher_is_better: true
metadata:
  - version: 0.0